version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql://username:password@localhost/your_db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
